import 'package:flutter/material.dart';
void main()=>runApp(const DuoPlayApp());
class DuoPlayApp extends StatelessWidget{const DuoPlayApp({super.key});@override Widget build(BuildContext context){return MaterialApp(debugShowCheckedModeBanner:false,title:'Duo Play',theme:ThemeData.dark().copyWith(scaffoldBackgroundColor:const Color(0xFF0F0F0F)),home:const HomeScreen());}}
class HomeScreen extends StatelessWidget{const HomeScreen({super.key});@override Widget build(BuildContext context){return Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.videogame_asset,size:80,color:Color(0xFFFFEB3B)),const SizedBox(height:20),const Text('Duo Play Ready',style:TextStyle(fontSize:28,color:Color(0xFFFFEB3B),fontWeight:FontWeight.bold)),const SizedBox(height:10),const Text('2 Player Fun Zone',style:TextStyle(color:Colors.white54)),const SizedBox(height:40),_btn(context,'Tic Tac Toe',Colors.amber,const TicTacToeScreen()),_btn(context,'Tap Battle',Colors.cyan,const TapBattleScreen()),_btn(context,'Dice Roll',Colors.greenAccent,const DiceScreen()),],),));}
Widget _btn(BuildContext c,String t,Color col,Widget screen){return Padding(padding:const EdgeInsets.only(bottom:12),child:SizedBox(width:double.infinity,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:col,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>screen)),child:Text(t,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),),),);}
class TicTacToeScreen extends StatefulWidget{const TicTacToeScreen({super.key});@override State<TicTacToeScreen> createState()=>_TicState();}
class _TicState extends State<TicTacToeScreen>{List<String> b=List.filled(9,'');bool oTurn=true;String? winner;void tap(int i){if(b[i]!=''||winner!=null) return;setState((){b[i]=oTurn?'O':'X';oTurn=!oTurn;check();});}void check(){List<List<int>> w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(var l in w){if(b[l[0]]!=''&&b[l[0]]==b[l[1]]&&b[l[0]]==b[l[2]]){winner=b[l[0]];}}if(!b.contains('')&&winner==null) winner='Draw';}@override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('Tic Tac Toe')),body:Column(children:[if(winner!=null) Padding(padding:const EdgeInsets.all(16),child:Text(winner=='Draw'?'Draw!':'Winner:  TextStyle(fontSize:24,color:Colors.amber))),Expanded(child:GridView.builder(padding:const EdgeInsets.all(16),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3),itemCount:9,itemBuilder:(c,i)=>GestureDetector(onTap:()=>tap(i),child:Container(margin:const EdgeInsets.all(6),decoration:BoxDecoration(color:Colors.white12,borderRadius:BorderRadius.circular(12)),child:Center(child:Text(b[i],style:const TextStyle(fontSize:40,fontWeight:FontWeight.bold))))))),ElevatedButton(onPressed:()=>setState((){b=List.filled(9,'');winner=null;}),child:const Text('Restart'))]));}}
class TapBattleScreen extends StatefulWidget{const TapBattleScreen({super.key});@override State<TapBattleScreen> createState()=>_TapState();}।import 'package:flutter/material.dart';
void main()=>runApp(const DuoPlayApp());
class DuoPlayApp extends StatelessWidget{const DuoPlayApp({super.key});@override Widget build(BuildContext context){return MaterialApp(debugShowCheckedModeBanner:false,title:'Duo Play',theme:ThemeData.dark().copyWith(scaffoldBackgroundColor:const Color(0xFF0F0F0F)),home:const HomeScreen());}}
class HomeScreen extends StatelessWidget{const HomeScreen({super.key});@override Widget build(BuildContext context){return Scaffold(body:Center(child:Padding(padding:const EdgeInsets.all(24),child:Column(mainAxisAlignment:MainAxisAlignment.center,children:[const Icon(Icons.videogame_asset,size:80,color:Color(0xFFFFEB3B)),const SizedBox(height:20),const Text('Duo Play Ready',style:TextStyle(fontSize:28,color:Color(0xFFFFEB3B),fontWeight:FontWeight.bold)),const SizedBox(height:10),const Text('2 Player Fun Zone',style:TextStyle(color:Colors.white54)),const SizedBox(height:40),_btn(context,'Tic Tac Toe',Colors.amber,const TicTacToeScreen()),_btn(context,'Tap Battle',Colors.cyan,const TapBattleScreen()),_btn(context,'Dice Roll',Colors.greenAccent,const DiceScreen()),],),));}
Widget _btn(BuildContext c,String t,Color col,Widget screen){return Padding(padding:const EdgeInsets.only(bottom:12),child:SizedBox(width:double.infinity,child:ElevatedButton(style:ElevatedButton.styleFrom(backgroundColor:col,foregroundColor:Colors.black,padding:const EdgeInsets.all(16)),onPressed:()=>Navigator.push(c,MaterialPageRoute(builder:(_)=>screen)),child:Text(t,style:const TextStyle(fontSize:18,fontWeight:FontWeight.bold)),),),);}
class TicTacToeScreen extends StatefulWidget{const TicTacToeScreen({super.key});@override State<TicTacToeScreen> createState()=>_TicState();}
class _TicState extends State<TicTacToeScreen>{List<String> b=List.filled(9,'');bool oTurn=true;String? winner;void tap(int i){if(b[i]!=''||winner!=null) return;setState((){b[i]=oTurn?'O':'X';oTurn=!oTurn;check();});}void check(){List<List<int>> w=[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];for(var l in w){if(b[l[0]]!=''&&b[l[0]]==b[l[1]]&&b[l[0]]==b[l[2]]){winner=b[l[0]];}}if(!b.contains('')&&winner==null) winner='Draw';}@override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const Text('Tic Tac Toe')),body:Column(children:[if(winner!=null) Padding(padding:const EdgeInsets.all(16),child:Text(winner=='Draw'?'Draw!':'Winner:  TextStyle(fontSize:24,color:Colors.amber))),Expanded(child:GridView.builder(padding:const EdgeInsets.all(16),gridDelegate:const SliverGridDelegateWithFixedCrossAxisCount(crossAxisCount:3),itemCount:9,itemBuilder:(c,i)=>GestureDetector(onTap:()=>tap(i),child:Container(margin:const EdgeInsets.all(6),decoration:BoxDecoration(color:Colors.white12,borderRadius:BorderRadius.circular(12)),child:Center(child:Text(b[i],style:const TextStyle(fontSize:40,fontWeight:FontWeight.bold))))))),ElevatedButton(onPressed:()=>setState((){b=List.filled(9,'');winner=null;}),child:const Text('Restart'))]));}}
class TapBattleScreen extends StatefulWidget{const TapBattleScreen({super.key});@override State<TapBattleScreen> createState()=>_TapState();}।
class _TapState extends State<TapBattleScreen>{int a=0,b=0;bool started=false;void start(){setState((){a=0;b=0;started=true;});Future.delayed(const Duration(seconds:10),(){if(mounted) setState(()=>started=false);});}@override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const

class _TapState extends State<TapBattleScreen>{int a=0,b=0;bool started=false;void start(){setState((){a=0;b=0;started=true;});Future.delayed(const Duration(seconds:10),(){if(mounted) setState(()=>started=false);});}@override Widget build(BuildContext context){return Scaffold(appBar:AppBar(title:const
